name: Monetics CI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [test, build]
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: go